name: Run tests
on: [push, pull_request]

jobs:
  buildtest:
    name: Lint, build and test
    strategy:
      matrix:
        node: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npx eslint --max-warnings 0 "**"
    - run: npm run build
    #- run: npm run test:ci
